version: '2'
services:
  wordpress:
    image: wordpress
  	ports:
    	- 8080:80
    environment:
      REDIS_HOST: redis
      GREETING: Servus!
  mysql:
    image: mariadb
	environment:
    	MYSQL_ROOT_PASSWORD: verySecure
    	MYSQL_DATABASE: wordpress
    	MYSQL_USER: wordpress
        MYSQL_PASSWORD: verySecure
    volumes:
    	mysql-db:/var/lib/mysql:rw

volumes:
  mysql-db:
    driver: rancher-nfs
